### PR TITLE
added 2 examples (Switch and RadioButtons)

### PR DESCRIPTION
**Pull request by nah0y**
If you could merge them so they are in the project for now, that would be great :p
Although, they are not working 100% because of the issues I've just created on github...

But having the demo scenes, you'll be able to see the issues easier and test if everything works. As you like ;)

### CODE REVIEW

**Comment by InvexGames** [comment]
I won't merge this just yet - gimme a few minutes to sort out those issues you just posted, then merge :)

**Comment by nah0y** [comment]
No problem, but at least take a look at the scenes so you can see the issues :)

**Comment by InvexGames** [comment]
Yep.

**Comment by InvexGames** [comment]
I think I need a coffee. I'm making so many easy mistakes here...

**Pull request closed without merging**
