### PR TITLE
removed interactable bool on the CheckBoxToggler script

### PR DESCRIPTION
**Pull request by nah0y**
directly use the toggle interactable bool instead of adding on on the CheckBoxToggler script

### CODE REVIEW

**Comment by nah0y** [comment]
Hum... you plan on keeping the Interactable boolean duplicated?

**Comment by InvexGames** [comment]
No, it already got removed when I redid it last night :P

**Comment by nah0y** [comment]
Are you sure? :)
Seems like it's still on master on the CheckBoxToggler script https://github.com/InvexGames/MaterialUI/blob/master/Scripts/CheckBoxToggler.cs

**Comment by InvexGames** [comment]
Oh, whoops.

**Pull request closed without merging**
